apiVersion: v1
kind: Namespace
metadata:
  name: otelcol-securityevent
  labels:
    name: otelcol-securityevent
    app.kubernetes.io/name: otelcol-securityevent
    app.kubernetes.io/component: collector

